CREATE 
  // CONTEXT MODELS
  (ctxm1:ContextModel {id: 'ctxm1'}),
  (appDom:ApplicationDomain {id: 'appDom1', name: 'Cinematography'}),
  (BR1:BusinessRule {id: 'BR1', Statement: 'Estado ∈ {Released, In Production, Post Production, Planned, Rumored, Canceled}', 
                     semantic: 'Movies are categorized according to their production status, and are divided into the categories "Released", "In Production", "Post Production", "Planned", "Rumored" and "Canceled".'}),
  (BR2:BusinessRule {id: 'BR2', Statement: 'Estado <> Released -> release_date = 1800-01-01', 
                     semantic: 'For movies whose status is not "Released", release_date must be set to the value 1800-01-01'}),
  (BR3:BusinessRule {id: 'BR3', Statement: 'format(release_date) = "YYYY-MM-DD"', 
                     semantic: 'Dates are represented in "YYYY-MM-DD" format'}),
  (BR4:BusinessRule {id: 'BR4', Statement: 'Rating ∈ [0, 10.0]', 
                     semantic: 'A movie rating is represented by a real number between 0 and 10'}),
  (UT1:UserType {id: 'UT1', name: 'Movie Performance Specialist', characteristics: 'Data Analyst'}),
  (T1:TaskAtHand {id: 'T1', name: 'Rating prediction', 
                  purpose: 'Predict movie ratings based on characteristics such as popularity, genre and duration.'}),
  (T2:TaskAtHand {id: 'T2', name: 'Release date trend identification', 
                  purpose: 'Identify trends in movie release dates.'}),
  (T3:TaskAtHand {id: 'T3', name: 'Success factor identification', 
                  purpose: 'Analyze the relationship between vote count, average rating and popularity to determine the factors that contribute to a movie\'s success.'}),
  (T4:TaskAtHand {id: 'T4', name: 'Analysis of effective marketing strategies for adult and family movies', 
                  purpose: 'Identify successful production companies based on the votes received by the movies they produced and analyze their strategies. A separate analysis must be done depending on whether the movie is for adults or suitable for all audiences.'}),
  (T1)-[:ASSIGNED_TO]->(UT1),
  (T2)-[:ASSIGNED_TO]->(UT1),
  (T3)-[:ASSIGNED_TO]->(UT1),
  (T4)-[:ASSIGNED_TO]->(UT1),

  (DQR1:DQRequirement {id: 'DQR1', 
                       statement: 'Previous day data must be updated and available every day at 9am (GMT-3).',
                       description: 'Data must be available in its most up-to-date version every day at 9am (GMT-3), as that is when the user application\'s predictive model scheduled execution begins.'}),
  (DQR2:DQRequirement {id: 'DQR2', 
                       statement: 'Data representing names must be spelled correctly.',
                       description: 'Fields of type "String" that represent country names, producer names, language names, or movie names must not contain spelling errors, and must use capitalization correctly.'}),
  (DQR3:DQRequirement {id: 'DQR3', 
                       statement: 'No data may take the value "" nor null.',
                       description: 'Cell values cannot be empty or null. Values that explicitly represent missing data, such as "No Data" or special dates, are allowed.'
                       }),
  (DQR4:DQRequirement {id: 'DQR4', 
                       statement: 'At least 90% of movies from the year 2000 onward must be present.',
                       description: 'Using the IMDB catalog as reference, coverage must be greater than or equal to 90% for movies released from the year 2000 onward.'}),
  (DQR1)-[:IMPOSED_BY]->(UT1),
  (DQR2)-[:IMPOSED_BY]->(UT1),
  (DQR3)-[:IMPOSED_BY]->(UT1),
  (DQR4)-[:IMPOSED_BY]->(UT1),

  (DF1:DataFiltering {id: 'DF1', 
                      statement: 'SELECT * FROM movies WHERE adult = "True"', 
                      description: 'Filter records that indicate the movie is for adults'}),
  (DF2:DataFiltering {id: 'DF2', 
                      statement: 'SELECT * FROM movies WHERE adult = "False"', 
                      description: 'Filter records that indicate the movie is suitable for all audiences'}),

  (DF1)-[:ADDRESSED_BY]->(T4),
  (DF2)-[:ADDRESSED_BY]->(T4),

  (DL1:DataLineage {id: 'DL1',
                    sources: '[kaggle, IMDB]',
                    lineage: 'movies_ML_lineage.json'}),

  (ctxm1)-[:HAS_COMPONENT]->(appDom),
  (ctxm1)-[:HAS_COMPONENT]->(BR1),
  (ctxm1)-[:HAS_COMPONENT]->(BR2),
  (ctxm1)-[:HAS_COMPONENT]->(BR3),
  (ctxm1)-[:HAS_COMPONENT]->(BR4),
  (ctxm1)-[:HAS_COMPONENT]->(UT1),
  (ctxm1)-[:HAS_COMPONENT]->(T1),
  (ctxm1)-[:HAS_COMPONENT]->(T2),
  (ctxm1)-[:HAS_COMPONENT]->(T3),
  (ctxm1)-[:HAS_COMPONENT]->(T4),
  (ctxm1)-[:HAS_COMPONENT]->(DQR1),
  (ctxm1)-[:HAS_COMPONENT]->(DQR2),
  (ctxm1)-[:HAS_COMPONENT]->(DQR3),
  (ctxm1)-[:HAS_COMPONENT]->(DQR4),
  (ctxm1)-[:HAS_COMPONENT]->(DF1),
  (ctxm1)-[:HAS_COMPONENT]->(DF2),
  (ctxm1)-[:HAS_COMPONENT]->(DL1),

  // ctxm2
  (ctxm2:ContextModel {id: 'ctxm2'}),
  (BR5:BusinessRule {id: 'BR5', statement: 'At least 90% of movies from the year 2000 onward must be present.',
                       semantic: 'Using the IMDB catalog as reference, coverage must be greater than or equal to 90% for movies released from the year 2000 onward.'}),
  (BR5)-[:DERIVED_FROM]->(DQR4),
  (SR2:SystemRequirement {id: 'SR2', 
                       statement: 'Previous day data must be updated and available every day at 8:45am (GMT-3).',
                       description: 'Data must be available in its most up-to-date version every day at 8:45am (GMT-3)'}),
  (SR2)-[:DERIVED_FROM]->(DQR1),

  (DL2:DataLineage {id: 'DL2',
                    sources: '[kaggle, IMDB]',
                    lineage: 'movie_ratings_lineage.json'}),

  (ctxm2)-[:HAS_COMPONENT]->(appDom),
  (ctxm2)-[:HAS_COMPONENT]->(BR1),
  (ctxm2)-[:HAS_COMPONENT]->(BR3),
  (ctxm2)-[:HAS_COMPONENT]->(BR4),
  (ctxm2)-[:HAS_COMPONENT]->(BR5),
  (ctxm2)-[:HAS_COMPONENT]->(SR2),
  (ctxm2)-[:HAS_COMPONENT]->(DL2),


  // ctxm3
  (ctxm3:ContextModel {id: 'ctxm3'}),
  (SR3:SystemRequirement {id: 'SR3', 
                       statement: 'Previous day data must be updated and available every day at 8:30am (GMT-3).',
                       description: 'Data must be available in its most up-to-date version every day at 8:30am (GMT-3)'}),
  (SR3)-[:DERIVED_FROM]->(SR2),
  (SR4:SystemRequirement {id: 'SR4', 
                       statement: 'UTF-8 support.',
                       description: 'All data characters must be encoded with UTF-8 compatible characters.'}),

  (OM1:OtherMetadata {id: 'OM1', 
                       path: 'https://www.kaggle.com/datasets/asaniczka/tmdb-movies-dataset-2023-930k-movies?select=TMDB_movie_dataset_v11.csv',
                       description: 'Metadata available at the dataset\'s original publication',
                       Author: 'asaniczka',
                       Last_update: '01/05/2025'}),

  (DL3:DataLineage {id: 'DL3',
                    sources: '[kaggle]',
                    lineage: ''}),

  (ctxm3)-[:HAS_COMPONENT]->(appDom),
  (ctxm3)-[:HAS_COMPONENT]->(BR1),
  (ctxm3)-[:HAS_COMPONENT]->(BR3),
  (ctxm3)-[:HAS_COMPONENT]->(BR5),
  (ctxm3)-[:HAS_COMPONENT]->(SR3),
  (ctxm3)-[:HAS_COMPONENT]->(SR4),
  (ctxm3)-[:HAS_COMPONENT]->(OM1),
  (ctxm3)-[:HAS_COMPONENT]->(DL3),


  // Create DQM1
  (dqm1:DQModel {id: 'dqm1'}),
  // Create dimensions
  (D1:DQDimension {id: 'D1', name: 'Accuracy', semantic: 'Concerns the correctness and precision with which real-world data is represented in an information system'})-[:D_IN]->(dqm1),
  (D2:DQDimension {id: 'D2', name: 'Completeness', semantic: 'Concerns the proportion of the real world that is represented in the information system'})-[:D_IN]->(dqm1),
  (D3:DQDimension {id: 'D3', name: 'Consistency', semantic: 'Concerns consistency among information system records'})-[:D_IN]->(dqm1),
  (D4:DQDimension {id: 'D4', name: 'Uniqueness', semantic: 'Concerns the degree of repetition of information system records'})-[:D_IN]->(dqm1),
  (D5:DQDimension {id: 'D5', name: 'Freshness', semantic: 'Concerns the degree to which data age affects its use'})-[:D_IN]->(dqm1),
  
  // Create factors
  (d1f1:DQFactor {id: 'D1F1', name: 'Syntactic Accuracy', semantic: 'Indicates how free of syntactic errors the data is'})-[:FACET_OF]->(D1),
  (d1f2:DQFactor {id: 'D1F2', name: 'Semantic Accuracy', semantic: 'Indicates how correct the data is relative to reality'})-[:FACET_OF]->(D1),
  (d2f1:DQFactor {id: 'D2F1', name: 'Density', semantic: 'Indicates the quantity of records with missing data'})-[:FACET_OF]->(D2),
  (d2f2:DQFactor {id: 'D2F2', name: 'Coverage', semantic: 'Indicates how much real-world data is represented in the system'})-[:FACET_OF]->(D2),
  (d3f1:DQFactor {id: 'D3F1', name: 'Domain Integrity', semantic: 'Indicates that represented data is within the domain, given its semantics and the application domain'})-[:FACET_OF]->(D3),
  (d3f2:DQFactor {id: 'D3F2', name: 'Intra-relation Integrity', semantic: 'Indicates that the values of two or more attributes of a record are consistent with each other'})-[:FACET_OF]->(D3),
  (d4f1:DQFactor {id: 'D4F1', name: 'Non-Duplication', semantic: 'Measures the degree of rows that are unique'})-[:FACET_OF]->(D4),
  (d5f1:DQFactor {id: 'D5F1', name: 'Timeliness', semantic: 'Measures how timely the data is at the time of reading'})-[:FACET_OF]->(D5),

  // Create metrics
  (m1:DQMetric {id: 'M1', name: 'DateFormat', purpose: 'Measures whether the format of a data value representing a date is correct relative to a specified format. Not measured for missing data.', granularity: 'cell', resultDomain: '{0,1}'})-[:MEASURES]->(d1f1),
  (m2:DQMetric {id: 'M2', name: 'CorrectName', purpose: 'Measures whether a data value representing a name is spelled correctly, regardless of capitalization', granularity: 'cell', resultDomain: '{0,1}'})-[:MEASURES]->(d1f1),
  (m3:DQMetric {id: 'M3', name: 'CorrectDate', purpose: 'Measures whether a date is correct given a reference', granularity: 'cell', resultDomain: '{0,1}'})-[:MEASURES]->(d1f2),
  (m4:DQMetric {id: 'M4', name: 'NonEmptyRatio', purpose: 'Measures the degree of non-missing values in a column. What is considered missing depends on the method.', granularity: 'column', resultDomain: '[0..1]'})-[:MEASURES]->(d2f1),
  (m5:DQMetric {id: 'M5', name: 'CoveragePercentage', purpose: 'Measures the percentage of values that are represented by some record in the dataset, relative to a reference', granularity: 'dataset', resultDomain: '[0..1]'})-[:MEASURES]->(d2f2),
  (m6:DQMetric {id: 'M6', name: 'StringInDomain', purpose: 'Measures whether a text-type data value is valid in the domain, given a reference', granularity: 'cell', resultDomain: '{0,1}'})-[:MEASURES]->(d3f1),
  (m7:DQMetric {id: 'M7', name: 'ValueInRange', purpose: 'Measures whether a numeric data value is positive', granularity: 'cell', resultDomain: '{0,1}'})-[:MEASURES]->(d3f1),
  (m8:DQMetric {id: 'M8', name: 'DateIntegrity', purpose: 'Measures whether a date is valid given another data value', granularity: 'cell pair', resultDomain: '{0,1}'})-[:MEASURES]->(d3f2),
  (m9:DQMetric {id: 'M9', name: 'UniqueKeyRatio', purpose: 'Measures the degree of dataset rows that are unique, according to an identifier column', granularity: 'dataset', resultDomain: '[0..1]'})-[:MEASURES]->(d4f1),
  (m10:DQMetric {id: 'M10', name: 'TimelinessScore', purpose: 'Calculates the difference in minutes between the time when data is needed and the time when it is updated', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d5f1),
  (m11:DQMetric {id: 'M11', name: 'Age', purpose: 'Calculates the time since the last data update, in a given time unit', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d5f1),

  // Methods
  (me1:DQMethod {id: 'ME1', name: 'verifyDateFormat', inputDataTypes: 'String, String', outputDataTypes: 'Boolean', algorithm: 'verifyDateFormat(data, format)'})-[:IMPLEMENTS]->(m1),
  (me2:DQMethod {id: 'ME2', name: 'verifyName', inputDataTypes: 'String, Dataset', outputDataTypes: 'Boolean', algorithm: 'compareNameWithReference(data, reference)'})-[:IMPLEMENTS]->(m2),
  (me3:DQMethod {id: 'ME3', name: 'verifyCorrectDate', inputDataTypes: 'Date, String, dataset', outputDataTypes: 'Boolean', algorithm: 'correctDate(date, title, reference)'})-[:IMPLEMENTS]->(m3),
  (me4:DQMethod {id: 'ME4', name: 'nonNullRatio', inputDataTypes: 'Object[]', outputDataTypes: 'Float', algorithm: 'nonNullRatio(column)'})-[:IMPLEMENTS]->(m4),
  (me5:DQMethod {id: 'ME5', name: 'nonNullNorNoDataRatio', inputDataTypes: 'Object[], String[]', outputDataTypes: 'Float', algorithm: 'nonNullNorNoDataRatio(column, ref)'})-[:IMPLEMENTS]->(m4),
  (me6:DQMethod {id: 'ME6', name: 'coveragePercentageRef', inputDataTypes: 'Object[], String[]', outputDataTypes: 'Float', algorithm: 'coveragePercentageRef(column, ref)'})-[:IMPLEMENTS]->(m5),
  (me7:DQMethod {id: 'ME7', name: 'statusInDomain', inputDataTypes: 'String, String[]', outputDataTypes: 'Boolean', algorithm: 'verifyStatus(status, possibleStatuses)'})-[:IMPLEMENTS]->(m6),
  (me8:DQMethod {id: 'ME8', name: 'valueInRange', inputDataTypes: 'Float, Float, Float', outputDataTypes: 'Boolean', algorithm: 'verifyNumberInRange(data, min, max)'})-[:IMPLEMENTS]->(m7),
  (me9:DQMethod {id: 'ME9', name: 'dateIntegrityReleased', inputDataTypes: 'Date, String', outputDataTypes: 'Boolean', algorithm: 'dateValidForStatus(date, status)'})-[:IMPLEMENTS]->(m8),
  (me10:DQMethod {id: 'ME10', name: 'uniqueKeyRatio', inputDataTypes: 'Object[][], Object[]', outputDataTypes: 'Float', algorithm: 'nonDuplicateRowRatio(dataset, column)'})-[:IMPLEMENTS]->(m9),
  (me11:DQMethod {id: 'ME11', name: 'timeliness9am', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'timelinessScore(dataset)'})-[:IMPLEMENTS]->(m10),
  (me12:DQMethod {id: 'ME12', name: 'ageInMinutes', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'staleness(dataset)'})-[:IMPLEMENTS]->(m11),

  (ame1:AppliedDQMethod {id: 'ame1', appliedTo: 'release_date'})-[:ASSOCIATED]->(me1),
  (ame2:AppliedDQMethod {id: 'ame2', appliedTo: 'title'})-[:ASSOCIATED]->(me2),
  (ame3:AppliedDQMethod {id: 'ame3', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me2),
  (ame4:AppliedDQMethod {id: 'ame4', appliedTo: 'release_date'})-[:ASSOCIATED]->(me3),
  (ame5:AppliedDQMethod {id: 'ame5', appliedTo: 'title'})-[:ASSOCIATED]->(me4),
  (ame6:AppliedDQMethod {id: 'ame6', appliedTo: 'genres'})-[:ASSOCIATED]->(me4),
  (ame7:AppliedDQMethod {id: 'ame7', appliedTo: 'release_date'})-[:ASSOCIATED]->(me4),
  (ame8:AppliedDQMethod {id: 'ame8', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me4),
  (ame9:AppliedDQMethod {id: 'ame9', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me4),
  (ame10:AppliedDQMethod {id: 'ame10', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me4),
  (ame11:AppliedDQMethod {id: 'ame11', appliedTo: 'genres'})-[:ASSOCIATED]->(me5),
  (ame12:AppliedDQMethod {id: 'ame12', appliedTo: 'release_date'})-[:ASSOCIATED]->(me5),
  (ame13:AppliedDQMethod {id: 'ame13', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me5),
  (ame14:AppliedDQMethod {id: 'ame14', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me5),
  (ame15:AppliedDQMethod {id: 'ame15', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me5),
  (ame16:AppliedDQMethod {id: 'ame16', appliedTo: ''})-[:ASSOCIATED]->(me6),
  (ame17:AppliedDQMethod {id: 'ame17', appliedTo: 'status'})-[:ASSOCIATED]->(me7),
  (ame18:AppliedDQMethod {id: 'ame18', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me8),
  (ame19:AppliedDQMethod {id: 'ame19', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me8),
  (ame20:AppliedDQMethod {id: 'ame20', appliedTo: 'release_date, status'})-[:ASSOCIATED]->(me9),
  (ame21:AppliedDQMethod {id: 'ame21', appliedTo: 'id'})-[:ASSOCIATED]->(me10),
  (ame22:AppliedDQMethod {id: 'ame22', appliedTo: ''})-[:ASSOCIATED]->(me11),
  (ame23:AppliedDQMethod {id: 'ame23', appliedTo: ''})-[:ASSOCIATED]->(me12),
  (ame1)-[:BELONGS_TO]->(dqm1),
  (ame2)-[:BELONGS_TO]->(dqm1),
  (ame3)-[:BELONGS_TO]->(dqm1),
  (ame4)-[:BELONGS_TO]->(dqm1),
  (ame5)-[:BELONGS_TO]->(dqm1),
  (ame6)-[:BELONGS_TO]->(dqm1),
  (ame7)-[:BELONGS_TO]->(dqm1),
  (ame8)-[:BELONGS_TO]->(dqm1),
  (ame9)-[:BELONGS_TO]->(dqm1),
  (ame10)-[:BELONGS_TO]->(dqm1),
  (ame11)-[:BELONGS_TO]->(dqm1),
  (ame12)-[:BELONGS_TO]->(dqm1),
  (ame13)-[:BELONGS_TO]->(dqm1),
  (ame14)-[:BELONGS_TO]->(dqm1),
  (ame15)-[:BELONGS_TO]->(dqm1),
  (ame16)-[:BELONGS_TO]->(dqm1),
  (ame17)-[:BELONGS_TO]->(dqm1),
  (ame18)-[:BELONGS_TO]->(dqm1),
  (ame19)-[:BELONGS_TO]->(dqm1),
  (ame20)-[:BELONGS_TO]->(dqm1),
  (ame21)-[:BELONGS_TO]->(dqm1),
  (ame22)-[:BELONGS_TO]->(dqm1),
  (ame23)-[:BELONGS_TO]->(dqm1),

  // Relationships between DQ Model 1 and Context Model 1
  (ctxm1)-[:CONTEXTUALIZES_DQM]->(dqm1),
  (D1)-[:SUGGESTED_BY]->(BR3),
  (D1)-[:SUGGESTED_BY]->(T3),
  (D1)-[:SUGGESTED_BY]->(DQR2),
  (D2)-[:SUGGESTED_BY]->(DQR3),
  (D2)-[:SUGGESTED_BY]->(DQR4),
  (D2)-[:SUGGESTED_BY]->(T1),
  (D2)-[:SUGGESTED_BY]->(T3),
  (D2)-[:SUGGESTED_BY]->(T4),
  (D3)-[:SUGGESTED_BY]->(BR1),
  (D3)-[:SUGGESTED_BY]->(BR2),
  (D3)-[:SUGGESTED_BY]->(BR4),
  (D3)-[:SUGGESTED_BY]->(T1),
  (D5)-[:SUGGESTED_BY]->(DQR1),
  (D2)-[:SUGGESTED_BY]->(DL1),
  (D3)-[:SUGGESTED_BY]->(DL1),
  (D4)-[:SUGGESTED_BY]->(DL1),
  (d1f1)-[:REPRESENTS]->(BR3),
  (d1f1)-[:REPRESENTS]->(DQR2),
  (d1f2)-[:REPRESENTS]->(T2),
  (d2f1)-[:REPRESENTS]->(DQR3),
  (d2f1)-[:REPRESENTS]->(DL1),
  (d2f1)-[:REPRESENTS]->(T1),
  (d2f1)-[:REPRESENTS]->(T3),
  (d2f1)-[:REPRESENTS]->(T4),
  (d2f2)-[:REPRESENTS]->(DQR4),
  (d3f1)-[:REPRESENTS]->(BR1),
  (d3f1)-[:REPRESENTS]->(BR4),
  (d3f1)-[:REPRESENTS]->(DL1),
  (d3f1)-[:REPRESENTS]->(T1),
  (d3f2)-[:REPRESENTS]->(BR2),
  (d4f1)-[:REPRESENTS]->(DL1),
  (d5f1)-[:REPRESENTS]->(DQR1),
  (m1)-[:INFLUENCED_BY]->(BR3),
  (m2)-[:INFLUENCED_BY]->(DQR2),
  (m3)-[:INFLUENCED_BY]->(T2),
  (m4)-[:INFLUENCED_BY]->(DQR3),
  (m4)-[:INFLUENCED_BY]->(DL1),
  (m4)-[:INFLUENCED_BY]->(T1),
  (m4)-[:INFLUENCED_BY]->(T3),
  (m4)-[:INFLUENCED_BY]->(T4),
  (m5)-[:INFLUENCED_BY]->(DQR4),
  (m6)-[:INFLUENCED_BY]->(BR1),
  (m7)-[:INFLUENCED_BY]->(BR4),
  (m7)-[:INFLUENCED_BY]->(T1),
  (m7)-[:INFLUENCED_BY]->(DL1),
  (m8)-[:INFLUENCED_BY]->(BR2),
  (m9)-[:INFLUENCED_BY]->(DL1),
  (m10)-[:INFLUENCED_BY]->(DQR1),
  (m11)-[:INFLUENCED_BY]->(DQR1),
  (me1)-[:USES]->(BR3),
  (me2)-[:USES]->(DQR2),
  (me3)-[:USES]->(T2),
  (me4)-[:USES]->(DQR3),
  (me4)-[:USES]->(DL1),
  (me5)-[:USES]->(T1),
  (me5)-[:USES]->(T3),
  (me5)-[:USES]->(T4),
  (me6)-[:USES]->(DQR4),
  (me7)-[:USES]->(BR1),
  (me8)-[:USES]->(BR4),
  (me8)-[:USES]->(T1),
  (me8)-[:USES]->(DL1),
  (me9)-[:USES]->(BR2),
  (me10)-[:USES]->(DL1),
  (me11)-[:USES]->(DQR1),
  (me12)-[:USES]->(DQR1),


  // Create DQM2
  (dqm2:DQModel {id: 'dqm2'}),
  (D1)-[:D_IN]->(dqm2),
  (D2)-[:D_IN]->(dqm2),
  (D3)-[:D_IN]->(dqm2),
  (D4)-[:D_IN]->(dqm2),
  (D5)-[:D_IN]->(dqm2),
  (me13:DQMethod {id: 'ME13', name: 'timeliness8_45am', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'timelinessScore(dataset)'})-[:IMPLEMENTS]->(m10),
  (ame24:AppliedDQMethod {id: 'ame24', appliedTo: 'release_date'})-[:ASSOCIATED]->(me1),
  (ame25:AppliedDQMethod {id: 'ame25', appliedTo: 'title'})-[:ASSOCIATED]->(me4),
  (ame26:AppliedDQMethod {id: 'ame26', appliedTo: 'genres'})-[:ASSOCIATED]->(me4),
  (ame27:AppliedDQMethod {id: 'ame27', appliedTo: 'release_date'})-[:ASSOCIATED]->(me4),
  (ame28:AppliedDQMethod {id: 'ame28', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me4),
  (ame29:AppliedDQMethod {id: 'ame29', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me4),
  (ame30:AppliedDQMethod {id: 'ame30', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me4),
  (ame31:AppliedDQMethod {id: 'ame31', appliedTo: ''})-[:ASSOCIATED]->(me6),
  (ame32:AppliedDQMethod {id: 'ame32', appliedTo: 'status'})-[:ASSOCIATED]->(me7),
  (ame33:AppliedDQMethod {id: 'ame33', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me8),
  (ame34:AppliedDQMethod {id: 'ame34', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me8),
  (ame35:AppliedDQMethod {id: 'ame35', appliedTo: 'id'})-[:ASSOCIATED]->(me10),
  (ame36:AppliedDQMethod {id: 'ame36', appliedTo: ''})-[:ASSOCIATED]->(me13),
  (ame37:AppliedDQMethod {id: 'ame37', appliedTo: ''})-[:ASSOCIATED]->(me12),
  (ame24)-[:BELONGS_TO]->(dqm2),
  (ame25)-[:BELONGS_TO]->(dqm2),
  (ame26)-[:BELONGS_TO]->(dqm2),
  (ame27)-[:BELONGS_TO]->(dqm2),
  (ame28)-[:BELONGS_TO]->(dqm2),
  (ame29)-[:BELONGS_TO]->(dqm2),
  (ame30)-[:BELONGS_TO]->(dqm2),
  (ame31)-[:BELONGS_TO]->(dqm2),
  (ame32)-[:BELONGS_TO]->(dqm2),
  (ame33)-[:BELONGS_TO]->(dqm2),
  (ame34)-[:BELONGS_TO]->(dqm2),
  (ame35)-[:BELONGS_TO]->(dqm2),
  (ame36)-[:BELONGS_TO]->(dqm2),
  (ame37)-[:BELONGS_TO]->(dqm2),

  // Relationships between DQ Model 2 and Context Model 2
  (ctxm2)-[:CONTEXTUALIZES_DQM]->(dqm2),
  (D2)-[:SUGGESTED_BY]->(BR5),
  (D2)-[:SUGGESTED_BY]->(DL2),
  (D3)-[:SUGGESTED_BY]->(DL2),
  (D4)-[:SUGGESTED_BY]->(DL2),
  (D5)-[:SUGGESTED_BY]->(SR2),
  (d2f1)-[:REPRESENTS]->(DL2),
  (d2f2)-[:REPRESENTS]->(BR5),
  (d3f1)-[:REPRESENTS]->(DL2),
  (d4f1)-[:REPRESENTS]->(DL2),
  (d5f1)-[:REPRESENTS]->(SR2),
  (m4)-[:INFLUENCED_BY]->(DL2),
  (m7)-[:INFLUENCED_BY]->(DL2),
  (m9)-[:INFLUENCED_BY]->(DL2),
  (m10)-[:INFLUENCED_BY]->(SR2),
  (m11)-[:INFLUENCED_BY]->(SR2),
  (me4)-[:USES]->(DL2),
  (me6)-[:USES]->(BR5),
  (me8)-[:USES]->(DL2),
  (me10)-[:USES]->(DL2),
  (me12)-[:USES]->(SR2),
  (me13)-[:USES]->(SR2),

  // Create DQM3
  (dqm3:DQModel {id: 'dqm3'}),
  (D1)-[:D_IN]->(dqm3),
  (D2)-[:D_IN]->(dqm3),
  (D3)-[:D_IN]->(dqm3),
  (D5)-[:D_IN]->(dqm3),
  (D6:DQDimension {id: 'D6', name: 'Data Volume', semantic: 'Concerns the quantity and size of data stored in the information system'})-[:D_IN]->(dqm3),
  (d6f1:DQFactor {id: 'D6F1', name: 'Volume', semantic: 'Measures the quantity of stored data'})-[:FACET_OF]->(D6),
  (m12:DQMetric {id: 'M12', name: 'RowCount', purpose: 'Calculates the number of rows in a dataset', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d6f1),
  (m13:DQMetric {id: 'M13', name: 'Size', purpose: 'Calculates the dataset size in some specified unit', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d6f1),
  (me14:DQMethod {id: 'ME14', name: 'timeliness8_30am', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'timelinessScore(dataset)'})-[:IMPLEMENTS]->(m10),
  (me15:DQMethod {id: 'ME15', name: 'countRows', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'countRows(dataset)'})-[:IMPLEMENTS]->(m12),
  (me16:DQMethod {id: 'ME16', name: 'byteSize', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'sizeInBytes(dataset)'})-[:IMPLEMENTS]->(m13),
  (ame38:AppliedDQMethod {id: 'ame38', appliedTo: 'release_date'})-[:ASSOCIATED]->(me1),
  (ame39:AppliedDQMethod {id: 'ame39', appliedTo: 'title'})-[:ASSOCIATED]->(me4),
  (ame40:AppliedDQMethod {id: 'ame40', appliedTo: 'genres'})-[:ASSOCIATED]->(me4),
  (ame41:AppliedDQMethod {id: 'ame41', appliedTo: 'release_date'})-[:ASSOCIATED]->(me4),
  (ame42:AppliedDQMethod {id: 'ame42', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me4),
  (ame43:AppliedDQMethod {id: 'ame43', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me4),
  (ame44:AppliedDQMethod {id: 'ame44', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me4),
  (ame45:AppliedDQMethod {id: 'ame45', appliedTo: 'status'})-[:ASSOCIATED]->(me7),
  (ame46:AppliedDQMethod {id: 'ame46', appliedTo: ''})-[:ASSOCIATED]->(me14),
  (ame47:AppliedDQMethod {id: 'ame47', appliedTo: ''})-[:ASSOCIATED]->(me12),
  (ame48:AppliedDQMethod {id: 'ame48', appliedTo: ''})-[:ASSOCIATED]->(me15),
  (ame49:AppliedDQMethod {id: 'ame49', appliedTo: ''})-[:ASSOCIATED]->(me16),
  (ame38)-[:BELONGS_TO]->(dqm3),
  (ame39)-[:BELONGS_TO]->(dqm3),
  (ame40)-[:BELONGS_TO]->(dqm3),
  (ame41)-[:BELONGS_TO]->(dqm3),
  (ame42)-[:BELONGS_TO]->(dqm3),
  (ame43)-[:BELONGS_TO]->(dqm3),
  (ame44)-[:BELONGS_TO]->(dqm3),
  (ame45)-[:BELONGS_TO]->(dqm3),
  (ame46)-[:BELONGS_TO]->(dqm3),
  (ame47)-[:BELONGS_TO]->(dqm3),
  (ame48)-[:BELONGS_TO]->(dqm3),
  (ame49)-[:BELONGS_TO]->(dqm3),

  // Relationships between DQ Model 3 and Context Model 3
  (ctxm3)-[:CONTEXTUALIZES_DQM]->(dqm3),
  (D2)-[:SUGGESTED_BY]->(OM1),
  (D5)-[:SUGGESTED_BY]->(SR3),
  (d2f1)-[:REPRESENTS]->(OM1),
  (d5f1)-[:REPRESENTS]->(SR3),
  (m4)-[:INFLUENCED_BY]->(OM1),
  (m10)-[:INFLUENCED_BY]->(SR3),
  (m11)-[:INFLUENCED_BY]->(SR3),
  (me4)-[:USES]->(OM1),
  (me12)-[:USES]->(SR3),
  (me14)-[:USES]->(SR3),

  (z1:Zone {name: 'landing-zone'}),
  (z2:Zone {name: 'raw-zone'}),
  (z3:Zone {name: 'trusted-zone'}),
  (z4:Zone {name: 'refined-zone'})
