CREATE 
  // CONTEXT MODELS
  (ctxm1:ContextModel {id: 'ctxm1'}),
  (appDom:ApplicationDomain {id: 'appDom1', name: 'Cinematografía'}),
  (BR1:BusinessRule {id: 'BR1', Statement: 'Estado ∈ {Released, In Production, Post Production, Planned, Rumored, Canceled}', 
                     semantic: 'Las películas se categorizan según su estado de producción, y se dividen en las categorías ‘Released’, ‘In Production’, ‘Post Production’, ‘Planned’, ‘Rumored’ y ‘Canceled.'}),
  (BR2:BusinessRule {id: 'BR2', Statement: 'Estado <> Released -> release_date = 1800-01-01', 
                     semantic: 'Para las películas cuyo estado no sea "Released", el release_date se debe setear al valor 1800-01-01'}),
  (BR3:BusinessRule {id: 'BR3', Statement: 'format(release_date) = "YYYY-MM-DD"', 
                     semantic: 'Las fechas se representan en formato "YYYY-MM-DD"'}),
  (BR4:BusinessRule {id: 'BR4', Statement: 'Rating ∈ [0, 10.0]', 
                     semantic: 'El rating de una película se representa con un número real entre 0 y 10'}),
  (UT1:UserType {id: 'UT1', name: 'Movie Performance Specialist', characteristics: 'Data Analyst'}),
  (T1:TaskAtHand {id: 'T1', name: 'Predicción de calificaciones', 
                  purpose: 'Predecir las calificaciones de películas en función de características como popularidad, género y duración.'}),
  (T2:TaskAtHand {id: 'T2', name: 'Identificación de tendencias de fechas de estreno', 
                  purpose: 'Identificar tendencias en las fechas de estreno de películas.'}),
  (T3:TaskAtHand {id: 'T3', name: 'Identificación de factores de éxito', 
                  purpose: 'Analizar la relación entre cantidad de votos, valoración promedio y popularidad para determinar los factores que contribuyen al éxito de una película.'}),
  (T4:TaskAtHand {id: 'T4', name: 'Análisis de estrategias efectivas de marketing para películas de adultos y niños', 
                  purpose: 'Identificar compañías de producción exitosas según los votos que recibieron las películas que produjeron y analizar sus estrategias. Se debe hacer un análisis distinto dependiendo de si la película es para adultos o apta para todo público.'}),
  (T1)-[:ASSIGNED_TO]->(UT1),
  (T2)-[:ASSIGNED_TO]->(UT1),
  (T3)-[:ASSIGNED_TO]->(UT1),
  (T4)-[:ASSIGNED_TO]->(UT1),

  (DQR1:DQRequirement {id: 'DQR1', 
                       statement: 'Los datos del día anterior deben estar actualizados y disponibles todos los días a las 9am (GMT-3).',
                       description: 'Los datos deben estar disponibles en su versión más actualizada todos los días a las 9am (GMT-3), ya que a esa hora comienza la ejecución programada del modelo predictivo de la aplicación del usuario.'}),
  (DQR2:DQRequirement {id: 'DQR2', 
                       statement: 'Los datos que representen nombres deben estar bien escritos.',
                       description: 'Los campos del tipo "String" que representen nombres de países, nombres de productores, nombres de idiomas, o nombres de películas no deben presentar faltas de ortografía, y deben hacer uso correcto de letras mayúsulas.'}),
  (DQR3:DQRequirement {id: 'DQR3', 
                       statement: 'Ningún dato puede tomar el valor "" ni null.',
                       description: 'Los valores de las celdas no pueden tener valores vacíos ni nulos. Sí se permiten valores que representen explícitamente la falta de datos, como "Sin Datos" o fechas especiales.'
                       }),
  (DQR4:DQRequirement {id: 'DQR4', 
                       statement: 'Deben estar presentes al menos 90% de las películas del año 2000 en adelante.',
                       description: 'Tomando como referencia el catálogo de IMDB, se debe contar con una cobertura mayor o igual a 90% para las películas estrenadas a partir del año 2000.'}),
  (DQR1)-[:IMPOSED_BY]->(UT1),
  (DQR2)-[:IMPOSED_BY]->(UT1),
  (DQR3)-[:IMPOSED_BY]->(UT1),
  (DQR4)-[:IMPOSED_BY]->(UT1),

  (DF1:DataFiltering {id: 'DF1', 
                      statement: 'SELECT * FROM movies WHERE adult = "True"', 
                      description: 'Filtrar registros que indiquen que la película es para adultos'}),
  (DF2:DataFiltering {id: 'DF2', 
                      statement: 'SELECT * FROM movies WHERE adult = "False"', 
                      description: 'Filtrar registros que indiquen que la película es apta para todo público'}),

  (DF1)-[:ADDRESSED_BY]->(T4),
  (DF2)-[:ADDRESSED_BY]->(T4),

  (DL1:DataLineage {id: 'DL1',
                    sources: '[kaggle, IMDB]',
                    lineage: 'movies_ML_lineage.json'}),

  (ctxm1)-[:HAS_COMPONENT]->(appDom),
  (ctxm1)-[:HAS_COMPONENT]->(BR1),
  (ctxm1)-[:HAS_COMPONENT]->(BR2),
  (ctxm1)-[:HAS_COMPONENT]->(BR3),
  (ctxm1)-[:HAS_COMPONENT]->(BR4),
  (ctxm1)-[:HAS_COMPONENT]->(UT1),
  (ctxm1)-[:HAS_COMPONENT]->(T1),
  (ctxm1)-[:HAS_COMPONENT]->(T2),
  (ctxm1)-[:HAS_COMPONENT]->(T3),
  (ctxm1)-[:HAS_COMPONENT]->(T4),
  (ctxm1)-[:HAS_COMPONENT]->(DQR1),
  (ctxm1)-[:HAS_COMPONENT]->(DQR2),
  (ctxm1)-[:HAS_COMPONENT]->(DQR3),
  (ctxm1)-[:HAS_COMPONENT]->(DQR4),
  (ctxm1)-[:HAS_COMPONENT]->(DF1),
  (ctxm1)-[:HAS_COMPONENT]->(DF2),
  (ctxm1)-[:HAS_COMPONENT]->(DL1),

  // ctxm2
  (ctxm2:ContextModel {id: 'ctxm2'}),
  (BR5:BusinessRule {id: 'BR5', statement: 'Deben estar presentes al menos 90% de las películas del año 2000 en adelante.',
                       semantic: 'Tomando como referencia el catálogo de IMDB, se debe contar con una cobertura mayor o igual a 90% para las películas estrenadas a partir del año 2000.'}),
  (BR5)-[:DERIVED_FROM]->(DQR4),
  (SR2:SystemRequirement {id: 'SR2', 
                       statement: 'Los datos del día anterior anterior deben estar actualizados y disponibles todos los días a las 8:45am (GMT-3).',
                       description: 'Los datos deben estar disponibles en su versión más actualizada todos los días a las 8:45am (GMT-3)'}),
  (SR2)-[:DERIVED_FROM]->(DQR1),

  (DL2:DataLineage {id: 'DL2',
                    sources: '[kaggle, IMDB]',
                    lineage: 'movie_ratings_lineage.json'}),

  (ctxm2)-[:HAS_COMPONENT]->(appDom),
  (ctxm2)-[:HAS_COMPONENT]->(BR1),
  (ctxm2)-[:HAS_COMPONENT]->(BR3),
  (ctxm2)-[:HAS_COMPONENT]->(BR4),
  (ctxm2)-[:HAS_COMPONENT]->(BR5),
  (ctxm2)-[:HAS_COMPONENT]->(SR2),
  (ctxm2)-[:HAS_COMPONENT]->(DL2),


  // ctxm3
  (ctxm3:ContextModel {id: 'ctxm3'}),
  (SR3:SystemRequirement {id: 'SR3', 
                       statement: 'Los datos del día anterior anterior deben estar actualizados y disponibles todos los días a las 8:30am (GMT-3).',
                       description: 'Los datos deben estar disponibles en su versión más actualizada todos los días a las 8:30am (GMT-3)'}),
  (SR3)-[:DERIVED_FROM]->(SR2),
  (SR4:SystemRequirement {id: 'SR4', 
                       statement: 'Soporte UTF-8.',
                       description: 'Todos los caracteres de los datos deben estar encodeados con caracteres compatibles con UTF-8.'}),

  (OM1:OtherMetadata {id: 'OM1', 
                       path: 'https://www.kaggle.com/datasets/asaniczka/tmdb-movies-dataset-2023-930k-movies?select=TMDB_movie_dataset_v11.csv',
                       description: 'Metadata available at the dataset’s origial publication',
                       Author: 'asaniczka',
                       Last_update: '01/05/2025'}),

  (DL3:DataLineage {id: 'DL3',
                    sources: '[kaggle]',
                    lineage: ''}),

  (ctxm3)-[:HAS_COMPONENT]->(appDom),
  (ctxm3)-[:HAS_COMPONENT]->(BR1),
  (ctxm3)-[:HAS_COMPONENT]->(BR3),
  (ctxm3)-[:HAS_COMPONENT]->(BR5),
  (ctxm3)-[:HAS_COMPONENT]->(SR3),
  (ctxm3)-[:HAS_COMPONENT]->(SR4),
  (ctxm3)-[:HAS_COMPONENT]->(OM1),
  (ctxm3)-[:HAS_COMPONENT]->(DL3),


  // Crear DQM1
  (dqm1:DQModel {id: 'dqm1'}),
  // Crear dimensiones
  (D1:DQDimension {id: 'D1', name: 'Exactitud', semantic: 'Concierne la correctitud y la precisión con que los datos del mundo real son representados en un sistema de información'})-[:D_IN]->(dqm1),
  (D2:DQDimension {id: 'D2', name: 'Completitud', semantic: 'Concierne la proporción del mundo real que está representado en el SI'})-[:D_IN]->(dqm1),
  (D3:DQDimension {id: 'D3', name: 'Consistencia', semantic: 'Concierne la consistencia entre los registros del SI'})-[:D_IN]->(dqm1),
  (D4:DQDimension {id: 'D4', name: 'Unicidad', semantic: 'Concierne el grado de repetición de los registros del SI'})-[:D_IN]->(dqm1),
  (D5:DQDimension {id: 'D5', name: 'Fescura', semantic: 'Concierne el grado en el que la edad de los datos afecta su uso'})-[:D_IN]->(dqm1),
  
  // Crear factores
  (d1f1:DQFactor {id: 'D1F1', name: 'Exactitud Sintáctica', semantic: 'Indica qué tan libre de errores sintácticos están los datos'})-[:FACET_OF]->(D1),
  (d1f2:DQFactor {id: 'D1F2', name: 'Exactitud Semántica', semantic: 'Indica qué tan correctos son los datos, relativos a la realidad'})-[:FACET_OF]->(D1),
  (d2f1:DQFactor {id: 'D2F1', name: 'Densidad', semantic: 'Indica qué cantidad de registros con datos faltantes hay'})-[:FACET_OF]->(D2),
  (d2f2:DQFactor {id: 'D2F2', name: 'Cobertura', semantic: 'Indica qué cantidad de datos de la realidad están representados en el sistema'})-[:FACET_OF]->(D2),
  (d3f1:DQFactor {id: 'D3F1', name: 'Integridad de Dominio', semantic: 'Indica que los datos representados estén en el dominio, dada su semántica y el dominio de aplicación'})-[:FACET_OF]->(D3),
  (d3f2:DQFactor {id: 'D3F2', name: 'Integridad Intrarrelación', semantic: 'Indica que los valores de dos o más atributos de un registro sean consistentes entre sí'})-[:FACET_OF]->(D3),
  (d4f1:DQFactor {id: 'D4F1', name: 'No-Duplicación', semantic: 'Mide el grado de filas que son únicas'})-[:FACET_OF]->(D4),
  (d5f1:DQFactor {id: 'D5F1', name: 'Oportunidad', semantic: 'Mide qué tan oportunos son los datos a la hora de su lectura'})-[:FACET_OF]->(D5),

  // Crear metricas
  (m1:DQMetric {id: 'M1', name: 'FormatoFecha', purpose: 'Mide si el formato de un dato que representa una fecha es correcto, relativo a un formato especificado. No se mide para datos faltantes.', granularity: 'celda', resultDomain: '{0,1}'})-[:MEASURES]->(d1f1),
  (m2:DQMetric {id: 'M2', name: 'NombreCorrecto', purpose: 'Mide si un dato que representa un nombre está bien escrito, sin imporar las mayúsculas', granularity: 'celda', resultDomain: '{0,1}'})-[:MEASURES]->(d1f1),
  (m3:DQMetric {id: 'M3', name: 'FechaCorrecta', purpose: 'Mide si una fecha es correcta, dado un referencial', granularity: 'celda', resultDomain: '{0,1}'})-[:MEASURES]->(d1f2),
  (m4:DQMetric {id: 'M4', name: 'RatioNoVacios', purpose: 'Mide el grado de valores no faltantes en una columna. Lo que se considera faltante depende del método.', granularity: 'columna', resultDomain: '[0..1]'})-[:MEASURES]->(d2f1),
  (m5:DQMetric {id: 'M5', name: 'PorcentajeCobertura', purpose: 'Mide el porcentaje de valores que se encuentran representados por algún registro del dataset, relativo a un referencial', granularity: 'dataset', resultDomain: '[0..1]'})-[:MEASURES]->(d2f2),
  (m6:DQMetric {id: 'M6', name: 'DatoEnDominioString', purpose: 'Mide si un dato de tipo texto es posible en el dominio, dado un referencial', granularity: 'celda', resultDomain: '{0,1}'})-[:MEASURES]->(d3f1),
  (m7:DQMetric {id: 'M7', name: 'DatoEnRango', purpose: 'Mide si un dato numérico es positivo', granularity: 'celda', resultDomain: '{0,1}'})-[:MEASURES]->(d3f1),
  (m8:DQMetric {id: 'M8', name: 'IntegridadFechas', purpose: 'Mide si una fecha es válida, dado otro dato', granularity: 'par de celdas', resultDomain: '{0,1}'})-[:MEASURES]->(d3f2),
  (m9:DQMetric {id: 'M9', name: 'RatioClavesUnicas', purpose: 'Mide el grado de filas de un dataset que son únicas, según una fila identificadora', granularity: 'dataset', resultDomain: '[0..1]'})-[:MEASURES]->(d4f1),
  (m10:DQMetric {id: 'M10', name: 'OportunidadPuntaje', purpose: 'Calcula la diferencia en minutos entre la hora en la que se necesitan los datos y la hora en la que se actualizan', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d5f1),
  (m11:DQMetric {id: 'M11', name: 'Edad', purpose: 'Calcula el tiempo desde la última actualización de los datos, en una unidad de tiempo dada', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d5f1),

  // Metodos
  (me1:DQMethod {id: 'ME1', name: 'verificarFormatoFecha', inputDataTypes: 'String, String', outputDataTypes: 'Boolean', algorithm: 'verificarFormatoFecha(dato, formato)'})-[:IMPLEMENTS]->(m1),
  (me2:DQMethod {id: 'ME2', name: 'verificarNombre', inputDataTypes: 'String, Dataset', outputDataTypes: 'Boolean', algorithm: 'compararNombreConReferencial(dato, referencial)'})-[:IMPLEMENTS]->(m2),
  (me3:DQMethod {id: 'ME3', name: 'verificarFechaCorrecta', inputDataTypes: 'Date, String, dataset', outputDataTypes: 'Boolean', algorithm: 'fechaCorrecta(fecha, titulo, referencial)'})-[:IMPLEMENTS]->(m3),
  (me4:DQMethod {id: 'ME4', name: 'ratioNoNulos', inputDataTypes: 'Object[]', outputDataTypes: 'Float', algorithm: 'ratioNoNulos(columna)'})-[:IMPLEMENTS]->(m4),
  (me5:DQMethod {id: 'ME5', name: 'ratioNoNulosNiSD', inputDataTypes: 'Object[], String[]', outputDataTypes: 'Float', algorithm: 'ratioNoNulosNiSD(columna, ref)'})-[:IMPLEMENTS]->(m4),
  (me6:DQMethod {id: 'ME6', name: 'porcentajeCoberturaRef', inputDataTypes: 'Object[], String[]', outputDataTypes: 'Float', algorithm: 'porcentajeCoberturaRef(columna, ref)'})-[:IMPLEMENTS]->(m5),
  (me7:DQMethod {id: 'ME7', name: 'StatusEnDominio', inputDataTypes: 'String, String[]', outputDataTypes: 'Boolean', algorithm: 'verificarStatus(status, posiblesStatus)'})-[:IMPLEMENTS]->(m6),
  (me8:DQMethod {id: 'ME8', name: 'DatoEnRango', inputDataTypes: 'Float, Float, Float', outputDataTypes: 'Boolean', algorithm: 'verificarNumeroEnRango(dato, min, max)'})-[:IMPLEMENTS]->(m7),
  (me9:DQMethod {id: 'ME9', name: 'IntegridadFechasReleased', inputDataTypes: 'Date, String', outputDataTypes: 'Boolean', algorithm: 'fechaEsValidaSegunStatus(fecha, status)'})-[:IMPLEMENTS]->(m8),
  (me10:DQMethod {id: 'ME10', name: 'RatioClavesUnicas', inputDataTypes: 'Object[][], Object[]', outputDataTypes: 'Float', algorithm: 'ratioNoDupFilas(dataset, columna)'})-[:IMPLEMENTS]->(m9),
  (me11:DQMethod {id: 'ME11', name: 'Oportunidad9am', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'timelinessScore(dataset)'})-[:IMPLEMENTS]->(m10),
  (me12:DQMethod {id: 'ME12', name: 'EdadMinutos', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'staleness(dataset)'})-[:IMPLEMENTS]->(m11),

  (ame1:AppliedDQMethod {id: 'ame1', appliedTo: 'release_date'})-[:ASSOCIATED]->(me1),
  (ame2:AppliedDQMethod {id: 'ame2', appliedTo: 'title'})-[:ASSOCIATED]->(me2),
  (ame3:AppliedDQMethod {id: 'ame3', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me2),
  (ame4:AppliedDQMethod {id: 'ame4', appliedTo: 'release_date'})-[:ASSOCIATED]->(me3),
  (ame5:AppliedDQMethod {id: 'ame5', appliedTo: 'title'})-[:ASSOCIATED]->(me4),
  (ame6:AppliedDQMethod {id: 'ame6', appliedTo: 'genres'})-[:ASSOCIATED]->(me4),
  (ame7:AppliedDQMethod {id: 'ame7', appliedTo: 'release_date'})-[:ASSOCIATED]->(me4),
  (ame8:AppliedDQMethod {id: 'ame8', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me4),
  (ame9:AppliedDQMethod {id: 'ame9', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me4),
  (ame10:AppliedDQMethod {id: 'ame10', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me4),
  (ame11:AppliedDQMethod {id: 'ame11', appliedTo: 'genres'})-[:ASSOCIATED]->(me5),
  (ame12:AppliedDQMethod {id: 'ame12', appliedTo: 'release_date'})-[:ASSOCIATED]->(me5),
  (ame13:AppliedDQMethod {id: 'ame13', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me5),
  (ame14:AppliedDQMethod {id: 'ame14', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me5),
  (ame15:AppliedDQMethod {id: 'ame15', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me5),
  (ame16:AppliedDQMethod {id: 'ame16', appliedTo: ''})-[:ASSOCIATED]->(me6),
  (ame17:AppliedDQMethod {id: 'ame17', appliedTo: 'status'})-[:ASSOCIATED]->(me7),
  (ame18:AppliedDQMethod {id: 'ame18', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me8),
  (ame19:AppliedDQMethod {id: 'ame19', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me8),
  (ame20:AppliedDQMethod {id: 'ame20', appliedTo: 'release_date, status'})-[:ASSOCIATED]->(me9),
  (ame21:AppliedDQMethod {id: 'ame21', appliedTo: 'id'})-[:ASSOCIATED]->(me10),
  (ame22:AppliedDQMethod {id: 'ame22', appliedTo: ''})-[:ASSOCIATED]->(me11),
  (ame23:AppliedDQMethod {id: 'ame23', appliedTo: ''})-[:ASSOCIATED]->(me12),
  (ame1)-[:BELONGS_TO]->(dqm1),
  (ame2)-[:BELONGS_TO]->(dqm1),
  (ame3)-[:BELONGS_TO]->(dqm1),
  (ame4)-[:BELONGS_TO]->(dqm1),
  (ame5)-[:BELONGS_TO]->(dqm1),
  (ame6)-[:BELONGS_TO]->(dqm1),
  (ame7)-[:BELONGS_TO]->(dqm1),
  (ame8)-[:BELONGS_TO]->(dqm1),
  (ame9)-[:BELONGS_TO]->(dqm1),
  (ame10)-[:BELONGS_TO]->(dqm1),
  (ame11)-[:BELONGS_TO]->(dqm1),
  (ame12)-[:BELONGS_TO]->(dqm1),
  (ame13)-[:BELONGS_TO]->(dqm1),
  (ame14)-[:BELONGS_TO]->(dqm1),
  (ame15)-[:BELONGS_TO]->(dqm1),
  (ame16)-[:BELONGS_TO]->(dqm1),
  (ame17)-[:BELONGS_TO]->(dqm1),
  (ame18)-[:BELONGS_TO]->(dqm1),
  (ame19)-[:BELONGS_TO]->(dqm1),
  (ame20)-[:BELONGS_TO]->(dqm1),
  (ame21)-[:BELONGS_TO]->(dqm1),
  (ame22)-[:BELONGS_TO]->(dqm1),
  (ame23)-[:BELONGS_TO]->(dqm1),

  // Relaciones entre DQ Model 1 y Context Model 1
  (ctxm1)-[:CONTEXTUALIZES_DQM]->(dqm1),
  (D1)-[:SUGGESTED_BY]->(BR3),
  (D1)-[:SUGGESTED_BY]->(T3),
  (D1)-[:SUGGESTED_BY]->(DQR2),
  (D2)-[:SUGGESTED_BY]->(DQR3),
  (D2)-[:SUGGESTED_BY]->(DQR4),
  (D2)-[:SUGGESTED_BY]->(T1),
  (D2)-[:SUGGESTED_BY]->(T3),
  (D2)-[:SUGGESTED_BY]->(T4),
  (D3)-[:SUGGESTED_BY]->(BR1),
  (D3)-[:SUGGESTED_BY]->(BR2),
  (D3)-[:SUGGESTED_BY]->(BR4),
  (D3)-[:SUGGESTED_BY]->(T1),
  (D5)-[:SUGGESTED_BY]->(DQR1),
  (D2)-[:SUGGESTED_BY]->(DL1),
  (D3)-[:SUGGESTED_BY]->(DL1),
  (D4)-[:SUGGESTED_BY]->(DL1),
  (d1f1)-[:REPRESENTS]->(BR3),
  (d1f1)-[:REPRESENTS]->(DQR2),
  (d1f2)-[:REPRESENTS]->(T2),
  (d2f1)-[:REPRESENTS]->(DQR3),
  (d2f1)-[:REPRESENTS]->(DL1),
  (d2f1)-[:REPRESENTS]->(T1),
  (d2f1)-[:REPRESENTS]->(T3),
  (d2f1)-[:REPRESENTS]->(T4),
  (d2f2)-[:REPRESENTS]->(DQR4),
  (d3f1)-[:REPRESENTS]->(BR1),
  (d3f1)-[:REPRESENTS]->(BR4),
  (d3f1)-[:REPRESENTS]->(DL1),
  (d3f1)-[:REPRESENTS]->(T1),
  (d3f2)-[:REPRESENTS]->(BR2),
  (d4f1)-[:REPRESENTS]->(DL1),
  (d5f1)-[:REPRESENTS]->(DQR1),
  (m1)-[:INFLUENCED_BY]->(BR3),
  (m2)-[:INFLUENCED_BY]->(DQR2),
  (m3)-[:INFLUENCED_BY]->(T2),
  (m4)-[:INFLUENCED_BY]->(DQR3),
  (m4)-[:INFLUENCED_BY]->(DL1),
  (m4)-[:INFLUENCED_BY]->(T1),
  (m4)-[:INFLUENCED_BY]->(T3),
  (m4)-[:INFLUENCED_BY]->(T4),
  (m5)-[:INFLUENCED_BY]->(DQR4),
  (m6)-[:INFLUENCED_BY]->(BR1),
  (m7)-[:INFLUENCED_BY]->(BR4),
  (m7)-[:INFLUENCED_BY]->(T1),
  (m7)-[:INFLUENCED_BY]->(DL1),
  (m8)-[:INFLUENCED_BY]->(BR2),
  (m9)-[:INFLUENCED_BY]->(DL1),
  (m10)-[:INFLUENCED_BY]->(DQR1),
  (m11)-[:INFLUENCED_BY]->(DQR1),
  (me1)-[:USES]->(BR3),
  (me2)-[:USES]->(DQR2),
  (me3)-[:USES]->(T2),
  (me4)-[:USES]->(DQR3),
  (me4)-[:USES]->(DL1),
  (me5)-[:USES]->(T1),
  (me5)-[:USES]->(T3),
  (me5)-[:USES]->(T4),
  (me6)-[:USES]->(DQR4),
  (me7)-[:USES]->(BR1),
  (me8)-[:USES]->(BR4),
  (me8)-[:USES]->(T1),
  (me8)-[:USES]->(DL1),
  (me9)-[:USES]->(BR2),
  (me10)-[:USES]->(DL1),
  (me11)-[:USES]->(DQR1),
  (me12)-[:USES]->(DQR1),


  // Crear DQM2
  (dqm2:DQModel {id: 'dqm2'}),
  (D1)-[:D_IN]->(dqm2),
  (D2)-[:D_IN]->(dqm2),
  (D3)-[:D_IN]->(dqm2),
  (D4)-[:D_IN]->(dqm2),
  (D5)-[:D_IN]->(dqm2),
  (me13:DQMethod {id: 'ME13', name: 'Oportunidad8:45am', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'timelinessScore(dataset)'})-[:IMPLEMENTS]->(m10),
  (ame24:AppliedDQMethod {id: 'ame24', appliedTo: 'release_date'})-[:ASSOCIATED]->(me1),
  (ame25:AppliedDQMethod {id: 'ame25', appliedTo: 'title'})-[:ASSOCIATED]->(me4),
  (ame26:AppliedDQMethod {id: 'ame26', appliedTo: 'genres'})-[:ASSOCIATED]->(me4),
  (ame27:AppliedDQMethod {id: 'ame27', appliedTo: 'release_date'})-[:ASSOCIATED]->(me4),
  (ame28:AppliedDQMethod {id: 'ame28', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me4),
  (ame29:AppliedDQMethod {id: 'ame29', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me4),
  (ame30:AppliedDQMethod {id: 'ame30', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me4),
  (ame31:AppliedDQMethod {id: 'ame31', appliedTo: ''})-[:ASSOCIATED]->(me6),
  (ame32:AppliedDQMethod {id: 'ame32', appliedTo: 'status'})-[:ASSOCIATED]->(me7),
  (ame33:AppliedDQMethod {id: 'ame33', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me8),
  (ame34:AppliedDQMethod {id: 'ame34', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me8),
  (ame35:AppliedDQMethod {id: 'ame35', appliedTo: 'id'})-[:ASSOCIATED]->(me10),
  (ame36:AppliedDQMethod {id: 'ame36', appliedTo: ''})-[:ASSOCIATED]->(me13),
  (ame37:AppliedDQMethod {id: 'ame37', appliedTo: ''})-[:ASSOCIATED]->(me12),
  (ame24)-[:BELONGS_TO]->(dqm2),
  (ame25)-[:BELONGS_TO]->(dqm2),
  (ame26)-[:BELONGS_TO]->(dqm2),
  (ame27)-[:BELONGS_TO]->(dqm2),
  (ame28)-[:BELONGS_TO]->(dqm2),
  (ame29)-[:BELONGS_TO]->(dqm2),
  (ame30)-[:BELONGS_TO]->(dqm2),
  (ame31)-[:BELONGS_TO]->(dqm2),
  (ame32)-[:BELONGS_TO]->(dqm2),
  (ame33)-[:BELONGS_TO]->(dqm2),
  (ame34)-[:BELONGS_TO]->(dqm2),
  (ame35)-[:BELONGS_TO]->(dqm2),
  (ame36)-[:BELONGS_TO]->(dqm2),
  (ame37)-[:BELONGS_TO]->(dqm2),

  // Relaciones entre DQ Model 2 y Context Model 2
  (ctxm2)-[:CONTEXTUALIZES_DQM]->(dqm2),
  (D2)-[:SUGGESTED_BY]->(BR5),
  (D2)-[:SUGGESTED_BY]->(DL2),
  (D3)-[:SUGGESTED_BY]->(DL2),
  (D4)-[:SUGGESTED_BY]->(DL2),
  (D5)-[:SUGGESTED_BY]->(SR2),
  (d2f1)-[:REPRESENTS]->(DL2),
  (d2f2)-[:REPRESENTS]->(BR5),
  (d3f1)-[:REPRESENTS]->(DL2),
  (d4f1)-[:REPRESENTS]->(DL2),
  (d5f1)-[:REPRESENTS]->(SR2),
  (m4)-[:INFLUENCED_BY]->(DL2),
  (m7)-[:INFLUENCED_BY]->(DL2),
  (m9)-[:INFLUENCED_BY]->(DL2),
  (m10)-[:INFLUENCED_BY]->(SR2),
  (m11)-[:INFLUENCED_BY]->(SR2),
  (me4)-[:USES]->(DL2),
  (me6)-[:USES]->(BR5),
  (me8)-[:USES]->(DL2),
  (me10)-[:USES]->(DL2),
  (me12)-[:USES]->(SR2),
  (me13)-[:USES]->(SR2),

  // Crear DQM3
  (dqm3:DQModel {id: 'dqm3'}),
  (D1)-[:D_IN]->(dqm3),
  (D2)-[:D_IN]->(dqm3),
  (D3)-[:D_IN]->(dqm3),
  (D5)-[:D_IN]->(dqm3),
  (D6:DQDimension {id: 'D6', name: 'Cantidad de Datos', semantic: 'Concierne la cantidad y el tamaño de los datos almacenados en el SI'})-[:D_IN]->(dqm3),
  (d6f1:DQFactor {id: 'D6F1', name: 'Volumen', semantic: 'Mide la cantidad de datos almacenados '})-[:FACET_OF]->(D6),
  (m12:DQMetric {id: 'M12', name: 'CantidadDeFilas', purpose: 'Calcula la cantidad de filas en un dataset', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d6f1),
  (m13:DQMetric {id: 'M13', name: 'Tamano', purpose: 'Calcula el tamaño del dataset en alguna unidad especificada', granularity: 'dataset', resultDomain: '(0..+inf)'})-[:MEASURES]->(d6f1),
  (me14:DQMethod {id: 'ME14', name: 'Oportunidad8:30am', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'timelinessScore(dataset)'})-[:IMPLEMENTS]->(m10),
  (me15:DQMethod {id: 'ME15', name: 'countFilas', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'countRows(dataset)'})-[:IMPLEMENTS]->(m12),
  (me16:DQMethod {id: 'ME16', name: 'byteSize', inputDataTypes: 'Object[][]', outputDataTypes: 'Integer', algorithm: 'sizeInBytes(dataset)'})-[:IMPLEMENTS]->(m13),
  (ame38:AppliedDQMethod {id: 'ame38', appliedTo: 'release_date'})-[:ASSOCIATED]->(me1),
  (ame39:AppliedDQMethod {id: 'ame39', appliedTo: 'title'})-[:ASSOCIATED]->(me4),
  (ame40:AppliedDQMethod {id: 'ame40', appliedTo: 'genres'})-[:ASSOCIATED]->(me4),
  (ame41:AppliedDQMethod {id: 'ame41', appliedTo: 'release_date'})-[:ASSOCIATED]->(me4),
  (ame42:AppliedDQMethod {id: 'ame42', appliedTo: 'vote_average'})-[:ASSOCIATED]->(me4),
  (ame43:AppliedDQMethod {id: 'ame43', appliedTo: 'vote_count'})-[:ASSOCIATED]->(me4),
  (ame44:AppliedDQMethod {id: 'ame44', appliedTo: 'production_countries'})-[:ASSOCIATED]->(me4),
  (ame45:AppliedDQMethod {id: 'ame45', appliedTo: 'status'})-[:ASSOCIATED]->(me7),
  (ame46:AppliedDQMethod {id: 'ame46', appliedTo: ''})-[:ASSOCIATED]->(me14),
  (ame47:AppliedDQMethod {id: 'ame47', appliedTo: ''})-[:ASSOCIATED]->(me12),
  (ame48:AppliedDQMethod {id: 'ame48', appliedTo: ''})-[:ASSOCIATED]->(me15),
  (ame49:AppliedDQMethod {id: 'ame49', appliedTo: ''})-[:ASSOCIATED]->(me16),
  (ame38)-[:BELONGS_TO]->(dqm3),
  (ame39)-[:BELONGS_TO]->(dqm3),
  (ame40)-[:BELONGS_TO]->(dqm3),
  (ame41)-[:BELONGS_TO]->(dqm3),
  (ame42)-[:BELONGS_TO]->(dqm3),
  (ame43)-[:BELONGS_TO]->(dqm3),
  (ame44)-[:BELONGS_TO]->(dqm3),
  (ame45)-[:BELONGS_TO]->(dqm3),
  (ame46)-[:BELONGS_TO]->(dqm3),
  (ame47)-[:BELONGS_TO]->(dqm3),
  (ame48)-[:BELONGS_TO]->(dqm3),
  (ame49)-[:BELONGS_TO]->(dqm3),

  // Relaciones entre DQ Model 3 y Context Model 3
  (ctxm3)-[:CONTEXTUALIZES_DQM]->(dqm3),
  (D2)-[:SUGGESTED_BY]->(OM1),
  (D5)-[:SUGGESTED_BY]->(SR3),
  (d2f1)-[:REPRESENTS]->(OM1),
  (d5f1)-[:REPRESENTS]->(SR3),
  (m4)-[:INFLUENCED_BY]->(OM1),
  (m10)-[:INFLUENCED_BY]->(SR3),
  (m11)-[:INFLUENCED_BY]->(SR3),
  (me4)-[:USES]->(OM1),
  (me12)-[:USES]->(SR3),
  (me14)-[:USES]->(SR3),

  (z1:Zone {name: 'landing-zone'}),
  (z2:Zone {name: 'raw-zone'}),
  (z3:Zone {name: 'trusted-zone'}),
  (z4:Zone {name: 'refined-zone'})